### ISSUE TITLE
`timeSecond.every(x)`,  x modulo 60 is a restriction?

### ISSUE THREAD

**Issue by ggarek** [d3/d3-time#16]
I try to use `d3time.timeSecond.every(x)` to create interval, which i use to generate ticks for time scale. The x is dynamic, meaning it depends on the time scale domain and range. Whenever x changes i create new interval for tick creation.

I am almost sure, that it is not a bug. But i would rather ask a question to be 100% sure, or may be to alter the behaviour of the `timeSecond` interval.

It seems, that x  in `d3time.timeSecond.every(x)` is rounded modulo 60. 
When i create interval with say `x=320`, and pass it to `timeScale.ticks` i get ticks distributed evenly with 60s distance between one another.

How can i solve my task, given the x may be greater then 60?

*I expected that `d3time.timeSecond(320)` creates an interval, which passed to `timeScale.ticks()` will produce ticks distributed evenly with 320s distance to one another.
May be i do not see the reason or the restriction which makes mentioned behaviour impossible*

p.s.: huh, sounds messy, sorry for that, i did my best to describe my case.
p.s.2: i will try to provide a sample code for clarification soon

**Comment by ggarek** [comment]
Assembled an example to demonstrate the case. [fiddle](https://jsfiddle.net/garek/wzp3fjvt/)

< Example code
```javascript
console.clear();

const ticksView = d3.timeSecond.every(320);
const tscale = d3.scaleTime();

const left = new Date(2015, 0, 1);
const right = new Date(left);
right.setHours(right.getHours() + 2);

const expectedAvgDistance = 320;
const duration = (right - left) / 1000;
const expectedNumberOfTicks = Math.floor(duration / expectedAvgDistance);

tscale.range([0, 1000]);
tscale.domain([left, right]);
const ticks = tscale.ticks(ticksView);
const { length: butGotTicks } = ticks;
const butGotAvgDistance = duration / butGotTicks;
console.log({ duration, expectedAvgDistance, expectedNumberOfTicks, butGotTicks,  butGotAvgDistance });
```

< Example output
```
butGotAvgDistance: 59.50413223140496
butGotTicks: 121
duration: 7200
expectedAvgDistance: 320
expectedNumberOfTicks: 22
```

**Comment by mbostock** [comment]
Yes, this is the behavior of [*interval*.every](https://github.com/d3/d3-time/blob/master/README.md#interval_every). Per the API Reference, emphasis added:

> Returns a [filtered](#interval_filter) view of this interval representing every *step*th date. **The meaning of *step* is dependent on this interval’s parent interval as defined by the field function.** For example, [timeMinute](#timeMinute).every(15) returns an interval representing every fifteen minutes, starting on the hour: :00, :15, :30, :45, <i>etc.</i> Note that for some intervals, the resulting dates may not be uniformly-spaced; [timeDay](#timeDay)’s parent interval is [timeMonth](#timeMonth), and thus the interval number resets at the start of each month. If *step* is not valid, returns null. If *step* is one, returns this interval.
>
> This method can be used in conjunction with [*interval*.range](#interval_range) to ensure that two overlapping ranges are consistent. For example, this range contains odd days:
>
> ```js
d3.timeDay.every(2).range(new Date(2015, 0, 1), new Date(2015, 0, 7));
// [Thu Jan 01 2015 00:00:00 GMT-0800 (PST),
//  Sat Jan 03 2015 00:00:00 GMT-0800 (PST),
//  Mon Jan 05 2015 00:00:00 GMT-0800 (PST)]
```
>
>As does this one:
>
>```js
d3.timeDay.every(2).range(new Date(2015, 0, 2), new Date(2015, 0, 8));
// [Sat Jan 03 2015 00:00:00 GMT-0800 (PST),
//  Mon Jan 05 2015 00:00:00 GMT-0800 (PST),
//  Wed Jan 07 2015 00:00:00 GMT-0800 (PST)]
```
>
> See also [*interval*.filter](#interval_filter).

In the case of seconds, the field number is in [0, 60] (though 60 only occurs with leap seconds), so higher values don’t make sense.

You probably want to define a custom time interval instead of using *interval*.every, such as:

```js
function fixedDuration(ms) {
  return d3.timeInterval(function(date) {
    date.setTime(Math.floor(date / ms) * ms);
  }, function(date, step) {
    date.setTime(+date + step * ms);
  }, function(start, end) {
    return (end - start) / ms;
  });
}

var interval = fixedDuration(320 * 1000); // Every 320s since UNIX epoch.
```
https://runkit.com/mbostock/5820c97c7757c900142a53e4

**Comment by ggarek** [comment]
@mbostock Awesome! Thank you very much! That is exactly what i need! 👍
