### ISSUE TITLE
timeInterval.every(x).count undefined for x > 1

### ISSUE THREAD

**Issue by Drahoslav7** [d3/d3-time#21]
Hi,
I want to be able to count boundaries of interval created from `every` method, but it seems not to wokr.

`d3.timeMinute.every(1).count(from, to);`  - this works, as expected
`d3.timeMinute.every(5).count(form, to);` - but in this case `count` is undefiend, why?

I think it is a bug.

**Comment by mbostock** [comment]
This is the expected behavior; filtered intervals do not support *interval*.count. Per the documentation for [*interval*.every](https://github.com/d3/d3-time/blob/master/README.md#interval_every):

> Returns a [filtered](https://github.com/d3/d3-time/blob/master/README.md#interval_filter) view of this interval representing every *step*th date. 

And for [*interval*.filter](https://github.com/d3/d3-time/blob/master/README.md#interval_filter):

> The returned filtered interval does not support [count](#interval_count).
