### ISSUE TITLE
Visualizing data based on Hijri date series 

### ISSUE THREAD

**Issue by Ashamandi** [d3/d3-time#23]
Hello,

As Islamic countries use Hijri date in their day-to-day activities. I suggest to add hijri calculations also to d3 to use its great power of visualizing time series data.

## From my point of view, I have two designs for that :
1. Integrate Hijri calculations module into d3-time library.
or 
2. Create a separate library let us call it "D3-time-hijri" as an example, it will be exactly like d3-time but generating Hijri dates

**Comment by mbostock** [comment]
This library doesn’t implement a calendaring system per se; it relies on JavaScript’s built-in Date class, which implements the Gregorian calendar. In theory, it would be possible to extend this library to support other calendaring systems, but I don’t have a sense of how practical that would be. I see two challenges: 

1. This library calls `new Date` internally (see [interval.js](https://github.com/d3/d3-time/blob/master/src/interval.js)), so if you want to substitute a different Date class (such as [hijri-date](https://github.com/abdennour/hijri-date)), you’ll need to modify the code to allow the Date constructor to be overridable. The Date substitute will also need to implement *date*.setTime.

2. The [built-in intervals](https://github.com/d3/d3-time/blob/master/README.md#intervals) may or may not be applicable in the non-Gregorian calendar system. Depending on which of these built-in intervals you want to reuse, the Date substitute will need to implement other methods. For example, the [day interval](https://github.com/d3/d3-time/blob/master/src/day.js) requires *date*.setHours, *date*.setDate, *date*.getDate and *date*.getTimezoneOffset.

I do not personally plan on implementing the Hijri calendar in JavaScript, so I am going to close this issue. But, if you wish to submit a pull request to address the first issue and allow the Date constructor to be overridable, I would be happy to review it, especially if you are willing to include a demonstration showing how to use it with other calendar systems. Thank you!

**Comment by mrashad2017** [comment]
Hello @mbostock ,

I do some investigation in [Hijri Date](https://github.com/abdennour/hijri-date) , I found some implementation need to be added as setTime, setHours, .. we request that from owner to be able to use it here. 
Can you advise the best way to use external library like Hijri Date, to D3-Time. Especially if this library contain "require" function between files. If there an example you can share this will be great.
