### ISSUE TITLE
bug where the same dates are not recognised as the same as each other (==), but are also not recognised as either less then or more then the other!

### ISSUE THREAD

**Issue by disleyland** [d3/d3-time#26]
tmp = d3.timeParse("%m/%Y")("12/2015");
tmp1 = [d3.timeParse("%m/%Y")("12/2015"),d3.timeParse("%m/%Y")("12/2015")]
tmp1.filter(function(d){return d==tmp}).length == 2; //should be true right, but the filter produces no matches.

oddly, tmp == tmp1[0] evaluates as false and tmp1[0]<tmp evaluates as false, but tmp1[0]<=tmp does evaluate as true!

**Comment by curran** [comment]
This is not to do with d3-time, but rather this is the behavior of Dates in JavaScript in general.

```js
var a = new Date("Mon, 30 Nov 2015 18:30:00 GMT");
var b = new Date("Mon, 30 Nov 2015 18:30:00 GMT");
a == b // Evaluates to false
a === b // Evaluates to false
```

**Comment by disleyland** [comment]
thanks curran.  Strange behaviour indeed!
