### ISSUE TITLE
d3.timeMonth.offset() returns not the best thing for final days of the month

### ISSUE THREAD

**Issue by DDDgfx** [d3/d3-time#34]
```
console.log(data.pDate); //Mon Dec 31 2018 00:00:00 GMT-0500 (Eastern Standard Time)
console.log(d3.timeMonth.offset(data.pDate, 2)); //Sun Mar 03 2019 00:00:00 GMT-0500 (Eastern Standard Time)
```

Im not sure this is "wrong", but it seems as though if I add month intervals from a date value that is higher than the shortest month of the year (29 or 28 i guess), I will either continue to accumulate extra days indefinitely, or just regularly run into the next month.

How can I insure the last day of the month always returns the last day of the month, but the 7th always returns the 7th?

**Comment by mbostock** [comment]
This is the expected behavior. Under the hood, it’s just calling *date*.setMonth(*date*.getMonth() + *offset*). If you want the last day of the previous month, *date*.setDate(-1) is probably what you want.
