### ISSUE TITLE
rangeInclusive

### ISSUE THREAD

**Issue by curran** [d3/d3-time#43]
Several times I've faced the situation where `.range` is desired, but with an inclusive range rather than an exclusive one.

Here's the solution I've been using so for this:

```js
timeDay.range(minDate, timeDay.offset(maxDate, 1))
```

It occurred to me that it might be nice to have an additional method that does this, maybe called `rangeInclusive`. That way the above code could be simplified to:

```js
timeDay.rangeInclusive(minDate, maxDate)
```

It's a minor improvement, but I think a viable improvement. Thoughts?

(FWIW here's the a full example with this need in context https://vizhub.com/curran/e7f414a4a4f942398749e8ea58fe2f4a?edit=files&file=index.js#L47 )

**Comment by Fil** [comment]
Cf. https://github.com/d3/d3-array/issues/90 & https://github.com/d3/d3/issues/137

**Comment by mbostock** [comment]
Would this work for you?

```js
timeDay.range(minDate, +maxDate + 1)
```

**Comment by mbostock** [comment]
As of #47, you can use d3.timeTicks for an inclusive range, and it also works for a descending range when *stop* is before *start*.

```js
d3.timeTicks(start, stop, d3.timeDay)
```
