### ISSUE TITLE
range in descending order?

### ISSUE THREAD

**Issue by t829702** [d3/d3-time#44]
I am expecting this to return current months' all dates in descending order, but it returns empty `[]` instead

```js
d3.utcDay.range(d3.utcMonth.ceil(now), d3.utcMonth.floor(now), -1)
```

I know it's easy to call `.reverse()` on the ascending range, but is there any particular reason no to have it?

**Comment by t829702** [comment]
feature request

**Comment by mbostock** [comment]
As of #47 you can use d3.utcTicks or d3.timeTicks for this purpose. For example:

```js
now = new Date()
start = d3.utcMonth.ceil(now)
stop = d3.utcMonth.floor(now)
d3.utcTicks(start, stop, d3.utcDay)
```
