### ISSUE TITLE
Incomplete TS type def for `timeTicks`?

### ISSUE THREAD

**Issue by julien-signal** [d3/d3-time#68]
Hi,

I'm quite new to TS and this probably isn't the repo for the fix but I wanted to hear from you anyway:

I've got a TS linting error on that that piece of code:

**Argument of type 'CountableTimeInterval' is not assignable to parameter of type 'number'**

```
timeTicks(min, max, timeDay)
```

Unless I'm mistaken the third parameter (`count`) can either be a number or a time interval. Code is working as expected and it's looking like a false negative from our TS linter probably because this [type definition](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/f6b37733d6a66dc9794fffebf9a4757008b5faa1/types/d3-time/index.d.ts#L666) is incomplete?

```typescript
export function timeTicks(start: Date, stop: Date, count: number): Date[];
```

Any thoughts?

**Comment by Fil** [comment]
This function's signature has not changed since it was introduced in https://github.com/d3/d3-time/pull/47 and allows count to be an interval.

(And yes, this discussion should be at https://github.com/DefinitelyTyped/DefinitelyTyped.)
