### ISSUE TITLE
Add ticks, tickInterval?

### ISSUE THREAD

**Issue by mbostock** [d3/d3-time#8]
Now that d3-array has [ticks](https://github.com/d3/d3-array#ticks) and [tickStep](https://github.com/d3/d3-array#tickStep) extracted from d3-scale, it seems like it’d be nice to provide an equivalent API for time-based ticks. We’d probably have a function named tickInterval instead of tickStep for time intervals, since it will return a time interval.

Related d3/d3-scale#36.

**Comment by curran** [comment]
:+1: tickInterval sounds great. This would round out the APIs nicely.

**Comment by curran** [comment]
The implementation of this logic is present in d3-scale as `tickInterval` in `time.js` https://github.com/d3/d3-scale/blob/master/src/time.js#L70
